### ISSUE TITLE
Not redirect to github repo

### ISSUE THREAD

**Issue by fakhrymubarak** [nawwab/tugasKu-withLogins#1]
On page [what](http://47.254.246.62/what), the GitHub button doesn't redirect to this GitHub repository [tugasKu-withLogins](https://github.com/nawwab/tugasKu-withLogins) but it redirects to [not found page 404 ](https://github.com/nawwab/tugasKu).

**Comment by nwxxb** [comment]
Thanks for your attention, I'll check it later
